services:
  # Prometheus Service
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net

  # Grafana Service
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - .env
    depends_on:
      - prometheus
    networks:
      - monitoring_net

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    env_file:
      - .env
    ports:
      - "9200:9200"
    networks:
      - monitoring_net

  # Logstash Service
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - monitoring_net

  # Kibana Service
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge
