global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['10.140.0.2:9100']
  - job_name: 'nginx'
    static_configs:
      - targets: ['10.140.0.2:9113']
